"""Candlesticks table

Revision ID: 57980dad0082
Revises: afee4b3b6728
Create Date: 2024-11-20 17:04:06.142824

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "57980dad0082"
down_revision: Union[str, None] = "afee4b3b6728"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candlestick",
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("dividends", sa.Float(), nullable=True),
        sa.Column("stock_splits", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("date", "symbol", "source"),
    )
    with op.batch_alter_table("candlestick", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_candlestick_date"), ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_candlestick_source"), ["source"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_candlestick_symbol"), ["symbol"], unique=False
        )

    with op.batch_alter_table("daily_ohlcv", schema=None) as batch_op:
        batch_op.drop_index("ix_daily_ohlcv_date")
        batch_op.drop_index("ix_daily_ohlcv_symbol")

    op.drop_table("daily_ohlcv")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_ohlcv",
        sa.Column("open", sa.FLOAT(), nullable=False),
        sa.Column("high", sa.FLOAT(), nullable=False),
        sa.Column("low", sa.FLOAT(), nullable=False),
        sa.Column("close", sa.FLOAT(), nullable=False),
        sa.Column("volume", sa.FLOAT(), nullable=False),
        sa.Column("dividends", sa.FLOAT(), nullable=True),
        sa.Column("stock_splits", sa.FLOAT(), nullable=True),
        sa.Column("date", sa.DATETIME(), nullable=False),
        sa.Column("symbol", sa.VARCHAR(), nullable=False),
        sa.Column("timezone", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("date", "symbol"),
    )
    with op.batch_alter_table("daily_ohlcv", schema=None) as batch_op:
        batch_op.create_index("ix_daily_ohlcv_symbol", ["symbol"], unique=False)
        batch_op.create_index("ix_daily_ohlcv_date", ["date"], unique=False)

    with op.batch_alter_table("candlestick", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candlestick_symbol"))
        batch_op.drop_index(batch_op.f("ix_candlestick_source"))
        batch_op.drop_index(batch_op.f("ix_candlestick_date"))

    op.drop_table("candlestick")
    # ### end Alembic commands ###
