"""sec

Revision ID: ac8512e066af
Revises: 4e44f10ee322
Create Date: 2025-11-19 16:35:30.792598

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac8512e066af"
down_revision: Union[str, None] = "4e44f10ee322"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secshareincrease", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secshareincrease", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###
