from datetime import date, datetime
from typing import Optional, Dict, Any, Annotated

from pydantic import (
    BaseModel,
    Field,
    ConfigDict,
    model_validator,
    field_validator,
    BeforeValidator,
)


def to_float(value: Any) -> Optional[float]:
    if value == "None":
        return None
    return float(value)


class BaseFinancials(BaseModel):
    __alias__: Dict[str, str] = {}
    __source__: Optional[str] = None
    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    date: date
    created_at: date
    symbol: str
    source: str

    @field_validator("date", mode="before")
    def _date_validator(cls, value: str | date) -> date:
        if isinstance(value, str):
            return datetime.strptime(value, "%Y-%m-%d").date()
        return value

    @model_validator(mode="before")
    def _validate(cls, metrics: Dict[str, Any]) -> Dict[str, Any]:
        if not cls.__source__:
            raise ValueError("No source specified for financial metrics")
        created_at = date.today()
        return (
            {"date": metrics.get("date", created_at)}
            | {
                cls.__alias__.get(key, key): value
                for key, value in metrics.items()
                if key in cls.__alias__
            }
            | {
                "created_at": created_at,
                "source": cls.__source__,
            }
        )


class FinancialMetrics(BaseFinancials):

    ebitda: Optional[float] = Field(
        None,
        description="Earnings before interest, taxes, depreciation, and amortization",
    )
    net_income: Optional[float] = Field(
        None, description="Total earnings or profit of the company"
    )
    pe_ratio: Optional[float] = Field(None)
    market_capitalization: Optional[float] = Field(None)
    basic_eps: Optional[float] = Field(
        None,
        description="Earnings per share for basic shares outstanding",
    )
    diluted_eps: Optional[float] = Field(
        None, alias="Diluted EPS", description="Earnings per share for diluted shares"
    )
    total_revenue: Optional[float] = Field(
        None,
        description="Total revenue generated by the company",
    )
    operating_revenue: Optional[float] = Field(
        None, description="Revenue from operating activities"
    )
    gross_profit: Optional[float] = Field(
        None,
        description="Revenue after deducting cost of goods sold",
    )
    total_expenses: Optional[float] = Field(
        None,
        description="Total expenses incurred by the company",
    )
    operating_income: Optional[float] = Field(
        None, description="Income generated from operations"
    )
    profit_margin: Optional[float] = Field(None, description="Net profit margin")
    cost_of_revenue: Optional[float] = Field(
        None, description="Cost incurred to generate revenue"
    )
    tax_provision: Optional[float] = Field(None, description="Provision for income tax")
    tax_rate: Optional[float] = Field(
        None, description="Effective tax rate used in calculations"
    )


class BalanceSheet(BaseFinancials):
    treasury_stock: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Shares held in the company's treasury"),
    ]

    common_stock_shares_outstanding: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Number of common shares outstanding"),
    ]

    common_stock: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Value of common stock issued"),
    ]

    short_long_term_debt_total: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Total short and long-term debt"),
    ]

    capital_lease_obligations: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Obligations under capital leases"),
    ]

    total_shareholder_equity: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Total equity held by shareholders"),
    ]

    retained_earnings: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Accumulated retained earnings"),
    ]

    total_liabilities: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Total liabilities, net of minority interest"),
    ]

    total_non_current_liabilities: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Total non-current liabilities"),
    ]

    other_non_current_liabilities: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Other non-current liabilities"),
    ]

    long_term_debt: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Long-term debt obligations"),
    ]

    total_current_liabilities: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Total current liabilities"),
    ]

    other_current_liabilities: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Other current liabilities"),
    ]

    current_debt: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Current debt obligations"),
    ]

    current_accounts_payable: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Accounts payable amount"),
    ]

    total_assets: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Total assets held by the company"),
    ]

    total_non_current_assets: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Total non-current assets"),
    ]

    other_non_current_assets: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Other non-current assets"),
    ]

    accumulated_depreciation_amortization_ppe: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(
            default=None,
            description="Accumulated depreciation and amortization for property, plant, and equipment",
        ),
    ]

    property_plant_equipment: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Gross property, plant, and equipment"),
    ]

    total_current_assets: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Total current assets"),
    ]

    other_current_assets: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Other current assets"),
    ]

    inventory: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Inventory held by the company"),
    ]

    current_net_receivables: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Net receivables amount"),
    ]

    cash_and_short_term_investments: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Cash and short-term investments"),
    ]

    cash_and_cash_equivalents_at_carrying_value: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Cash and cash equivalents at carrying value"),
    ]


class CashFlow(BaseFinancials):
    operating_cash_flow: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Cash flow generated from operating activities")
    ]
    change_in_operating_liabilities: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Changes in operating liabilities"
    )]
    change_in_working_capital: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Changes in working capital from operating activities")
    ]
    change_in_other_working_capital: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Changes in other working capital from operating activities")
    ]
    change_in_receivables: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Changes in accounts receivable balance")
    ]
    change_in_inventory: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Changes in inventory levels")
    ]
    depreciation_amortization_depletion: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Total depreciation, depletion, and amortization expenses")
    ]
    capital_expenditure: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Capital expenditures for fixed assets")
    ]
    cash_flow_from_investing_activities: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Cash flow generated or used in investing activities")
    ]
    financing_cash_flow: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Cash flow generated or used in financing activities")
    ]
    repurchase_of_capital_stock: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Payments made for repurchase of common stock")
    ]
    cash_dividends_paid: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Cash dividends paid to shareholders")
    ]
    common_stock_dividend_paid: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Dividends paid on common stock")
    ]
    proceeds_from_issuance_of_common_stock: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Proceeds from issuance of common stock")
    ]
    changes_in_cash: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Net changes in cash and cash equivalents")
    ]
    net_income_from_continuing_operations: Annotated[
        Optional[float],
        BeforeValidator(to_float),
        Field(default=None, description="Net income from continuing operations")
    ]
